# SPDX-License-Identifier: Apache-2.0
mode: production

hostname:
  hostname: https://sso.example.com
  admin: https://admin-sso.example.com

database:
  external:
    vendor: postgres
    host: postgresql-rw.default.svc
    port: 5432
    name: keycloak
    username: keycloak
    existingSecret: keycloak-db

resources:
  requests:
    cpu: "1"
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 4Gi
priorityClassName: platform-critical

replicaCount: 2

pdb:
  enabled: true
