annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update dbchecker image version to 1.38.0
      links:
        - name: dbchecker
          url: https://hub.docker.com/r/library/busybox
    - kind: changed
      description: Update ini-file-initializer image version to 1.38.0
      links:
        - name: ini-file-initializer
          url: https://hub.docker.com/r/library/busybox
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |-
    - name: mlflow
      image: burakince/mlflow:3.14.0
    - name: oauth2-proxy
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.3
    - name: dbchecker
      image: library/busybox:1.38.0
    - name: ini-file-initializer
      image: library/busybox:1.38.0
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/community-charts/helm-charts
    - name: Chart Usage Page
      url: https://community-charts.github.io/docs/charts/mlflow/usage
    - name: Upstream Project
      url: https://github.com/burakince/mlflow
  artifacthub.io/maintainers: |
    - name: burakince
      email: burak.ince@linux.org.tr
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/screenshots: |-
    - title: Quickstart UI screenshot
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/quickstart/quickstart_ui_screenshot.png
    - title: OSS registry 1 register
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_1_register.png
    - title: OSS Registry 2 dialog
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_2_dialog.png
    - title: OSS Registry 3 overview
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_3_overview.png
    - title: OSS Registry 3b version
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_3b_version.png
    - title: OSS Registry 4 version
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_4_model.png
    - title: OSS Registry 4b version
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_4b_model_alias.png
    - title: OSS Registry 5 transition
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_5_version.png
    - title: OSS Registry 6 transition
      url: https://raw.githubusercontent.com/mlflow/mlflow/refs/heads/master/docs/static/images/oss_registry_6_version.png
  artifacthub.io/signKey: |
    fingerprint: 939B1A0ED8AAA8E722ACCDB3B6A012EE8A76426A
    url: https://keybase.io/communitycharts/pgp_keys.asc
apiVersion: v2
appVersion: 3.14.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 18.7.6
- condition: mysql.enabled
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 14.0.3
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 5.4.0
description: A Helm chart for Mlflow open source platform for the machine learning
  lifecycle
home: https://mlflow.org
icon: https://raw.githubusercontent.com/mlflow/mlflow/master/assets/logo.svg
keywords:
- docker
- machine-learning
- ai
- ml
- model-management
- mlflow
- mlflow-tracking-server
- mlflow-docker
- mlflow-tracking
- mlflow-kube
kubeVersion: '>=1.16.0-0'
maintainers:
- email: burak.ince@linux.org.tr
  name: burakince
  url: https://www.burakince.com
name: mlflow
sources:
- https://github.com/community-charts/helm-charts
- https://github.com/burakince/mlflow
- https://github.com/mlflow/mlflow
type: application
version: 1.11.2
