apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: victoria-metrics
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: "admin"
        admin-password: "{{ .admin_password }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .oauth_client_secret }}"
  data:
  - secretKey: oauth_client_secret
    remoteRef:
      key: grafana
      property: client-secret
  - secretKey: admin_password
    remoteRef:
      key: grafana
      property: admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: victoria-metrics-vault-token
  namespace: victoria-metrics
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: victoria-metrics-vault-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: victoria-metrics/vault-token
      property: token
