apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoria-metrics-dcgm-exporter
  namespace: victoria-metrics
  labels:
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
spec:
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  namespaceSelector:
    matchNamespaces:
      - gpu-operator
  endpoints:
    - port: gpu-metrics
      interval: 5s
