apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: victoria-metrics-istio-ztunnel
  namespace: victoria-metrics
  labels:
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
spec:
  selector:
    matchLabels:
      app: ztunnel
  namespaceSelector:
    matchNames:
      - istio-system
  podMetricsEndpoints:
    - port: ztunnel-stats
      path: /stats/prometheus
      interval: 5s
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: victoria-metrics-istio-management-gateway
  namespace: victoria-metrics
  labels:
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: management-gateway
  namespaceSelector:
    matchNames:
      - istio-system
  podMetricsEndpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 5s
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: victoria-metrics-istio-service-gateway
  namespace: victoria-metrics
  labels:
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: service-gateway
  namespaceSelector:
    matchNames:
      - istio-system
  podMetricsEndpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 5s
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: victoria-metrics-istio-waypoint
  namespace: victoria-metrics
  labels:
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-class-name: istio-waypoint
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 5s
