{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  ingress:
    - from:
        {{- if .Values.networkPolicy.ingress.allowSameNamespace }}
        - podSelector: {}
        {{- end }}
        {{- with .Values.networkPolicy.ingress.extraFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        {{- if .Values.metrics.enabled }}
        - protocol: TCP
          port: {{ .Values.service.metricsPort }}
        {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- if .Values.networkPolicy.egress.allowSameNamespacePostgreSQL }}
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- end }}
    {{- if .Values.networkPolicy.egress.allowDNS }}
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    {{- if .Values.networkPolicy.egress.allowHTTPS }}
    - ports:
        - protocol: TCP
          port: 443
    {{- end }}
    {{- with .Values.networkPolicy.egress.extraTo }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
