{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- include "postgresql.validatePasswordGeneration" . -}}
{{- include "postgresql.validateExternalSecrets" . -}}
{{- if and (not .Values.auth.existingSecret) (not (include "postgresql.authSecretManagedByExternalSecret" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.existingSecretPostgresPasswordKey }}: {{ include "postgresql.postgresPassword" . | b64enc | quote }}
  {{ .Values.auth.existingSecretUserPasswordKey }}: {{ include "postgresql.userPassword" . | b64enc | quote }}
  {{- if eq .Values.architecture "replication" }}
  {{ .Values.auth.existingSecretReplicationPasswordKey }}: {{ include "postgresql.replicationPassword" . | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if and (include "postgresql.backupEnabled" .) (not .Values.backup.s3.existingSecret) }}
{{- if not (include "postgresql.backupSecretManagedByExternalSecret" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.backupSecretName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.backup.s3.existingSecretAccessKeyKey }}: {{ .Values.backup.s3.accessKey | quote }}
  {{ .Values.backup.s3.existingSecretSecretKeyKey }}: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
{{- end }}
