{{/* SPDX-License-Identifier: Apache-2.0 */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.clientServiceName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
  selector:
    {{- include "postgresql.componentLabels" (dict "root" . "role" (ternary "primary" "standalone" (eq .Values.architecture "replication"))) | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.metricsServiceName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    monitoring.helmforge.dev/enabled: "true"
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "postgresql.componentLabels" (dict "root" . "role" (ternary "primary" "standalone" (eq .Values.architecture "replication"))) | nindent 4 }}
{{- end }}
{{- if eq .Values.architecture "replication" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.primaryServiceName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  {{- with .Values.service.primaryAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
  selector:
    {{- include "postgresql.componentLabels" (dict "root" . "role" "primary") | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.primaryMetricsServiceName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    monitoring.helmforge.dev/enabled: "true"
    app.kubernetes.io/role: primary
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "postgresql.componentLabels" (dict "root" . "role" "primary") | nindent 4 }}
{{- end }}
{{- if gt (int .Values.replication.readReplicas.replicaCount) 0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.replicasServiceName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  {{- with .Values.service.replicasAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
  selector:
    {{- include "postgresql.componentLabels" (dict "root" . "role" "replica") | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.replicasMetricsServiceName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    monitoring.helmforge.dev/enabled: "true"
    app.kubernetes.io/role: replica
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "postgresql.componentLabels" (dict "root" . "role" "replica") | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
