apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-env-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-username: "{{ .admin_username }}"
        admin-password: "{{ .admin_password }}"
        database-password: "{{ .database_password }}"
        client-secret: "{{ .client_secret }}"
        argocd-client-secret: "{{ .argocd_client_secret }}"
        grafana-client-secret: "{{ .grafana_client_secret }}"
        argo-workflows-client-secret: "{{ .argo_workflows_client_secret }}"
        trusted-addresses: "{{ .trusted_addresses }}"
        google-client-id: "{{ .google_client_id }}"
        google-client-secret: "{{ .google_client_secret }}"
  data:
  - secretKey: admin_username
    remoteRef:
      key: keycloak
      property: admin-username
  - secretKey: admin_password
    remoteRef:
      key: keycloak
      property: admin-password
  - secretKey: database_password
    remoteRef:
      key: keycloak
      property: database-password
  - secretKey: client_secret
    remoteRef:
      key: oauth2-proxy
      property: client-secret
  - secretKey: argocd_client_secret
    remoteRef:
      key: argocd
      property: client-secret
  - secretKey: grafana_client_secret
    remoteRef:
      key: grafana
      property: client-secret
  - secretKey: argo_workflows_client_secret
    remoteRef:
      key: argo-workflows
      property: client-secret
  - secretKey: trusted_addresses
    remoteRef:
      key: keycloak
      property: trusted-addresses
  - secretKey: google_client_id
    remoteRef:
      key: keycloak
      property: google-client-id
  - secretKey: google_client_secret
    remoteRef:
      key: keycloak
      property: google-client-secret

