apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-db-secrets
  namespace: argo-workflows
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argo-workflows-db-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-username
    remoteRef:
      key: argo-workflows
      property: database-username
  - secretKey: database-password
    remoteRef:
      key: argo-workflows
      property: database-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-server-sso
  namespace: argo-workflows
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argo-server-sso
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: "argo-workflows"
        client-secret: "{{ .client_secret }}"
  data:
  - secretKey: client_secret
    remoteRef:
      key: argo-workflows
      property: client-secret
