{{- if and (.Values.controller.service.enabled) (.Values.controller.serviceMonitor.enabled) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kgateway.labels" . | nindent 4 }}
    {{- with .Values.controller.serviceMonitor.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.controller.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "kgateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
{{- end -}}
