apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sub-kube-state-metrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/shared-charts/kube-state-metrics
  destination:
    server: '{{server}}'
    namespace: kube-state-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
