apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-secrets
  namespace: valkey
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: valkey-secrets
    creationPolicy: Owner
  data:
  - secretKey: valkey-password
    remoteRef:
      key: redis
      property: redis-password
