apiVersion: v1
kind: ServiceAccount
metadata:
  name: valkey
  namespace: valkey
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-pvc
  namespace: valkey
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      serviceAccountName: valkey
      containers:
      - name: valkey
        image: valkey/valkey:9.1.0-alpine
        command:
        - valkey-server
        - --requirepass
        - $(VALKEY_PASS)
        env:
        - name: VALKEY_PASS
          valueFrom:
            secretKeyRef:
              name: valkey-secrets
              key: valkey-password
        ports:
        - containerPort: 6379
          name: valkey
        volumeMounts:
        - mountPath: /data
          name: valkeydata
      volumes:
      - name: valkeydata
        persistentVolumeClaim:
          claimName: valkey-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: valkey
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: valkey
