annotations:
  artifacthub.io/category: database
  artifacthub.io/changes: |
    - kind: changed
      description: "bump mysql to 9.7.1 (#583)"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Official Website
      url: https://www.mysql.com
    - name: Documentation
      url: https://helmforge.dev/docs/charts/mysql
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/mysql
    - name: support
      url: https://github.com/helmforgedev/charts/issues
  artifacthub.io/maintainers: |
    - name: HelmForge
      email: berlofa@helmforge.dev
    - name: Maicon Berlofa
      email: maicon.berloffa@gmail.com
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/helmforge/phpmyadmin
  artifacthub.io/signKey: |
    fingerprint: 6748042FBAD8C2E11C65E564170D55148EB88A9D
    url: https://repo.helmforge.dev/pgp-public-key.asc
  helmforge.dev/maturity: stable
  helmforge.dev/repository: https://repo.helmforge.dev
  helmforge.dev/signed: gpg+cosign
apiVersion: v2
appVersion: 9.7.1
description: MySQL for Kubernetes with explicit standalone and replication modes
home: https://helmforge.dev
icon: https://helmforge.dev/icons/charts/mysql.png
keywords:
- mysql
- database
- replication
kubeVersion: '>=1.26.0-0'
maintainers:
- name: helmforgedev
- name: mberlofa
name: mysql
sources:
- https://github.com/helmforgedev/charts
- https://hub.docker.com/_/mysql
type: application
version: 2.0.2
