apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-secrets
  namespace: mlflow
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mlflow-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        database-uri: "postgresql://{{ .username | toString }}:{{ .password | toString }}@postgres.postgres.svc:5432/mlflow"
        database-username: "{{ .username | toString }}"
        database-password: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      key: mlflow
      property: database-password
  - secretKey: username
    remoteRef:
      key: mlflow
      property: database-username
