{{- if and .Values.auth.enabled (not .Values.auth.existingAdminSecret.name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-auth-admin-secret
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ required "auth.adminUsername must be specified" .Values.auth.adminUsername | b64enc }}
  password: {{ required "auth.adminPassword must be specified" .Values.auth.adminPassword | b64enc }}
{{- end }}
