{{- if .Values.oauth2Proxy.enabled }}
{{- if .Values.oauth2Proxy.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.oauth2ProxySecretName" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.oauth2Proxy.provider.clientID }}
  {{ .Values.oauth2Proxy.existingSecret.clientIDKey }}: "{{ .Values.oauth2Proxy.provider.clientID }}"
  {{- end }}
  {{- if .Values.oauth2Proxy.provider.clientSecret }}
  {{ .Values.oauth2Proxy.existingSecret.clientSecretKey }}: "{{ .Values.oauth2Proxy.provider.clientSecret }}"
  {{- end }}
  {{- if .Values.oauth2Proxy.cookieSecret }}
  {{ .Values.oauth2Proxy.existingSecret.cookieSecretKey }}: "{{ .Values.oauth2Proxy.cookieSecret }}"
  {{- end }}
{{- end }}
{{- end }}
