{{- if and .Values.oidcAuth.enabled (eq .Values.oidcAuth.existingSecret.name "") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-oidc-auth-secret
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.oidcAuth.clientSecret }}
  {{ .Values.oidcAuth.existingSecret.clientSecretKey }}: {{ .Values.oidcAuth.clientSecret | quote }}
  {{- end }}
{{- end }}
