{{- if and .Values.ldapAuth.encodedTrustedCACertificate (not .Values.ldapAuth.externalSecretForTrustedCACertificate) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-trusted-ca-cert-secret
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.ldapAuth.encodedTrustedCACertificate }}
{{- end }}
