# SPDX-License-Identifier: Apache-2.0
# External Secrets Operator v1 example. The SecretStore/ClusterSecretStore must
# already exist and be allowed to read the referenced remote keys.

auth:
  database: app
  username: app

tls:
  enabled: true
  requireSecureTransport: true
  volumePermissions:
    enabled: true
  client:
    enabled: true
    sslMode: REQUIRED

backup:
  enabled: true
  s3:
    endpoint: https://s3.amazonaws.com
    bucket: my-mysql-backups

externalSecrets:
  enabled: true
  secretStoreRef:
    name: production-secrets
    kind: ClusterSecretStore
  auth:
    enabled: true
    rootPasswordRemoteRef:
      key: prod/mysql/auth
      property: root-password
    userPasswordRemoteRef:
      key: prod/mysql/auth
      property: user-password
    replicationPasswordRemoteRef:
      key: prod/mysql/auth
      property: replication-password
  tls:
    enabled: true
    caRemoteRef:
      key: prod/mysql/tls
      property: ca.crt
    certRemoteRef:
      key: prod/mysql/tls
      property: tls.crt
    keyRemoteRef:
      key: prod/mysql/tls
      property: tls.key
  backup:
    enabled: true
    accessKeyRemoteRef:
      key: prod/mysql/backup
      property: access-key
    secretKeyRemoteRef:
      key: prod/mysql/backup
      property: secret-key
