# SPDX-License-Identifier: Apache-2.0
architecture: standalone

auth:
  existingSecret: mysql-auth

initdb:
  scripts:
    10-extra.sql: |
      CREATE TABLE IF NOT EXISTS example (
        id INT PRIMARY KEY
      );

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
