# SPDX-License-Identifier: Apache-2.0
architecture: replication

auth:
  existingSecret: mysql-auth

replication:
  source:
    persistence:
      enabled: true
      size: 50Gi
  readReplicas:
    replicaCount: 2
    persistence:
      enabled: true
      size: 50Gi
