# SPDX-License-Identifier: Apache-2.0
architecture: replication

auth:
  existingSecret: mysql-auth

replication:
  source:
    resourcesPreset: medium
    persistence:
      enabled: true
      size: 100Gi
  readReplicas:
    replicaCount: 3
    resourcesPreset: medium
    probes:
      requireReadOnly: true
      requireRunningReplication: true
    persistence:
      enabled: true
      size: 100Gi
  binlog:
    retentionDays: 14
  replicaTuning:
    parallelWorkers: 8

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
