# SPDX-License-Identifier: Apache-2.0
architecture: replication

auth:
  existingSecret: mysql-auth

replication:
  source:
    resourcesPreset: medium
    persistence:
      enabled: true
      size: 100Gi
  readReplicas:
    replicaCount: 2
    resourcesPreset: small
    persistence:
      enabled: true
      size: 100Gi

metrics:
  enabled: true
  resourcesPreset: small
