# SPDX-License-Identifier: Apache-2.0
auth:
  existingSecret: mysql-auth

tls:
  enabled: true
  existingSecret: mysql-tls
  requireSecureTransport: true
  client:
    enabled: true
    sslMode: REQUIRED

networkPolicy:
  enabled: true
  metrics:
    enabled: true

metrics:
  enabled: true

standalone:
  persistence:
    enabled: true
    size: 20Gi
