apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-kyverno
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/shared-charts/kyverno
    helm:
      releaseName: kyverno
      skipCrds: true # CRDs pre-installed via bootstrap
      values: |
        crds:
          install: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
