apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sub-victoria-metrics-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/01-system/sub/victoria-metrics/manifests
  destination:
    server: '{{server}}'
    namespace: victoria-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
