apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-keycloak-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Run in wave 1 (needs to create the secret before keycloak chart wave 2 installs)
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # GitOps repository URL
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/01-system/main/keycloak/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
