apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-kgateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/shared-charts/kgateway/charts/kgateway
    helm:
      releaseName: kgateway
      skipCrds: true # CRDs pre-installed via bootstrap
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kgateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
