annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - add `nodePort` support for `Service` resources
    - bump VictoriaLogs version to [v1.51.0](https://github.com/VictoriaMetrics/VictoriaLogs/releases/tag/v1.51.0).
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-logs-cluster
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/victorialogs/cluster/
    - name: Changelog
      url: https://docs.victoriametrics.com/helm/victoria-logs-cluster/changelog/
  artifacthub.io/readme: |
    # VictoriaLogs Cluster Helm chart

    Chart documentation is available [here](https://docs.victoriametrics.com/helm/victoria-logs-cluster/).
    Changelog is [here](https://docs.victoriametrics.com/helm/victoria-logs-cluster/changelog/).
apiVersion: v2
appVersion: v1.51.0
dependencies:
- condition: vector.enabled
  name: vector
  repository: https://helm.vector.dev
  version: 0.56.*
- name: victoria-metrics-common
  repository: oci://ghcr.io/victoriametrics/helm-charts
  version: 0.3.*
description: The VictoriaLogs cluster Helm chart deploys VictoriaLogs cluster database
  in Kubernetes.
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victorialogs
- logs
- kubernetes
- observability
- logsql
kubeVersion: '>=1.25.0-0'
name: victoria-logs-cluster
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.2.7
