{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.realmImport.enabled .Values.realmImport.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.realmImportConfigMapName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  {{- range $name, $content := .Values.realmImport.files }}
  {{ $name }}: |
{{ $content | indent 4 }}
  {{- end }}
{{- end }}
