{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.externalSecrets.enabled }}
{{- include "keycloak.validateAll" . -}}
{{- if .Values.externalSecrets.admin.enabled }}
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "keycloak.fullname" . }}-admin
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ include "keycloak.adminSecretName" . | quote }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy | quote }}
  data:
    - secretKey: {{ .Values.admin.existingSecretUsernameKey | quote }}
      remoteRef:
        {{- toYaml .Values.externalSecrets.admin.usernameRemoteRef | nindent 8 }}
    - secretKey: {{ .Values.admin.existingSecretPasswordKey | quote }}
      remoteRef:
        {{- toYaml .Values.externalSecrets.admin.passwordRemoteRef | nindent 8 }}
{{- end }}
{{- if .Values.externalSecrets.database.enabled }}
---
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "keycloak.fullname" . }}-database
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ include "keycloak.databaseSecretName" . | quote }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy | quote }}
  data:
    - secretKey: {{ include "keycloak.databaseSecretPasswordKey" . | quote }}
      remoteRef:
        {{- toYaml .Values.externalSecrets.database.passwordRemoteRef | nindent 8 }}
{{- end }}
{{- if .Values.externalSecrets.truststore.enabled }}
---
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "keycloak.fullname" . }}-truststore
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ include "keycloak.truststoreSecretName" . | quote }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy | quote }}
  data:
    {{- toYaml .Values.externalSecrets.truststore.data | nindent 4 }}
{{- end }}
{{- end }}
