{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  ingress:
    - from:
        {{- if .Values.networkPolicy.ingress.allowSameNamespace }}
        - podSelector: {}
        {{- end }}
        {{- with .Values.networkPolicy.ingress.extraFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.http.port }}
    - from:
        {{- if .Values.networkPolicy.management.allowSameNamespace }}
        - podSelector: {}
        {{- end }}
        {{- with .Values.networkPolicy.management.extraFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.http.managementPort }}
    {{- if and .Values.networkPolicy.clustering.enabled (gt (int .Values.replicaCount) 1) }}
    - from:
        - podSelector:
            matchLabels:
              {{- include "keycloak.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 7800
        - protocol: TCP
          port: 57800
    {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- if .Values.networkPolicy.egress.allowDns }}
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.egress.dnsNamespaceSelector | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.egress.dnsPodSelector | nindent 14 }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    {{- if and .Values.networkPolicy.egress.allowDatabase (include "keycloak.hasDatabase" .) .Values.networkPolicy.egress.databaseTo }}
    - to:
        {{- toYaml .Values.networkPolicy.egress.databaseTo | nindent 8 }}
      ports:
        - protocol: TCP
          port: {{ include "keycloak.databasePort" . }}
    {{- end }}
    {{- with .Values.networkPolicy.egress.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
