{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and (not .Values.admin.existingSecret) (not (include "keycloak.adminSecretManagedByExternalSecret" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.adminSecretName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.admin.existingSecretUsernameKey }}: {{ .Values.admin.username | b64enc | quote }}
  {{ .Values.admin.existingSecretPasswordKey }}: {{ include "keycloak.adminPassword" . | b64enc | quote }}
{{- end }}
{{- if and (include "keycloak.hasDatabase" .) (not (and (eq (include "keycloak.databaseMode" .) "external") .Values.database.external.existingSecret)) (not (include "keycloak.databaseSecretManagedByExternalSecret" .)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.databaseSecretName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "keycloak.databaseSecretPasswordKey" . }}: {{ include "keycloak.databasePassword" . | b64enc | quote }}
{{- end }}
{{- if and (include "keycloak.backupEnabled" .) (not .Values.backup.s3.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.backupSecretName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.backup.s3.existingSecretAccessKeyKey }}: {{ .Values.backup.s3.accessKey | quote }}
  {{ .Values.backup.s3.existingSecretSecretKeyKey }}: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
