{{/* SPDX-License-Identifier: Apache-2.0 */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-management
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
  {{- with .Values.service.managementAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- with .Values.service.managementIpFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.managementIpFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: management
      port: {{ .Values.http.managementPort }}
      targetPort: management
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
