# SPDX-License-Identifier: Apache-2.0
# CI: Backup enabled
backup:
  enabled: true
  suspend: true
  s3:
    endpoint: https://minio.example.com
    bucket: mysql-backups
    accessKey: test-access
    secretKey: test-secret
