# SPDX-License-Identifier: Apache-2.0
auth:
  existingSecret: mysql-auth

standalone:
  persistence:
    enabled: false

extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: mysql-auth
    type: Opaque
    stringData:
      mysql-root-password: root-password
      mysql-user-password: app-password
      mysql-replication-password: replication-password
