# SPDX-License-Identifier: Apache-2.0
# CI scenario: validate an additional initdb ConfigMap mount.
initdb:
  existingConfigMap: mysql-initdb-extra

standalone:
  persistence:
    enabled: false

extraManifests:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: mysql-initdb-extra
    data:
      10-extra.sql: |
        CREATE TABLE IF NOT EXISTS ci_extra_configmap (id INT PRIMARY KEY);
