# SPDX-License-Identifier: Apache-2.0
architecture: replication

replication:
  binlog:
    format: MIXED
    retentionDays: 14
    syncBinlog: 1
  replicaTuning:
    parallelWorkers: 8
  readReplicas:
    replicaCount: 3
