# SPDX-License-Identifier: Apache-2.0
architecture: replication

replication:
  source:
    resourcesPreset: medium
    persistence:
      enabled: false
  readReplicas:
    replicaCount: 2
    resourcesPreset: small
    persistence:
      enabled: false

metrics:
  enabled: true
  resourcesPreset: small
