# SPDX-License-Identifier: Apache-2.0
auth:
  existingSecret: mysql-auth

tls:
  enabled: true
  existingSecret: mysql-tls
  requireSecureTransport: true
  client:
    enabled: true

standalone:
  persistence:
    enabled: false

extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: mysql-auth
    type: Opaque
    stringData:
      mysql-root-password: root-password
      mysql-user-password: app-password
      mysql-replication-password: replication-password
  - apiVersion: v1
    kind: Secret
    metadata:
      name: mysql-tls
    type: kubernetes.io/tls
    stringData:
      ca.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDDTCCAfWgAwIBAgIUU8i0NyFmqFcuP/v+ZKPoFRC3e3YwDQYJKoZIhvcNAQEL
        BQAwFjEUMBIGA1UEAwwLbXlzcWwubG9jYWwwHhcNMjYwNjE1MjIwMTU5WhcNMjcw
        NjE1MjIwMTU5WjAWMRQwEgYDVQQDDAtteXNxbC5sb2NhbDCCASIwDQYJKoZIhvcN
        AQEBBQADggEPADCCAQoCggEBALkffpwujJC+fTK+nFS0RtKtuEyGPx+bgeXIclzw
        gg7cuXg2E+mIRdNUbH1s1BqwVVeDAPPIPfCPmP7REQoMKTJUGu7kDauVA65lGBKQ
        WR8pMHObLVJEXRp7EOIxhJf1B5tYv9BwyzRswGL7/Dgd7vIm12YfpNVNJrVuf0Zx
        ovk0XTsYFdsNcoIkxOqJ4/WeZSaoM5bLpldDVfbSv+qZC9xVnio/ApJjSSbXbMRZ
        eoQzR+2xtoBM6zbYlGEW2nALqgIo9xjfXMRIlrdbujVdIyomIdqAQriMU3yD6v82
        L/1c7TbthHK8AEjGlXzJ7tGL0dcSIcrNhts2djucsO2vRekCAwEAAaNTMFEwHQYD
        VR0OBBYEFJemKcn2GrmrXf/c6QzHgfW6AnSiMB8GA1UdIwQYMBaAFJemKcn2Grmr
        Xf/c6QzHgfW6AnSiMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
        AIAWVhWxKp/vxBTJtmY/DJm+3bFH+zcYikOHEGn28hhbL7noINN1UGeA2nAA0m1C
        cT+tVCYxztwH8A46SxJ+SKY5fkfWiSGkRQt/nQUcVgga6k851yhCS7jQ8QM5qtvd
        12Rfohwpm2iLiDFLvmUK2C1T4faBMaaJRuuVKCPM7v5so6z3eTLh7bLnoxSbBtKV
        6oQliMX2J9pMT1g0ILhU/9NypvLpf6fsRyM128cB0+5AUIdtAALymwIrc6aKALum
        cY7v7e7TzkKfnW+KIkJkdjxevHxCHob0TpiMo95ok3QZbmG027YE2+VN46JheZAz
        uxkOVPWSzrSt0loNHu7Hkok=
        -----END CERTIFICATE-----
      tls.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDDTCCAfWgAwIBAgIUU8i0NyFmqFcuP/v+ZKPoFRC3e3YwDQYJKoZIhvcNAQEL
        BQAwFjEUMBIGA1UEAwwLbXlzcWwubG9jYWwwHhcNMjYwNjE1MjIwMTU5WhcNMjcw
        NjE1MjIwMTU5WjAWMRQwEgYDVQQDDAtteXNxbC5sb2NhbDCCASIwDQYJKoZIhvcN
        AQEBBQADggEPADCCAQoCggEBALkffpwujJC+fTK+nFS0RtKtuEyGPx+bgeXIclzw
        gg7cuXg2E+mIRdNUbH1s1BqwVVeDAPPIPfCPmP7REQoMKTJUGu7kDauVA65lGBKQ
        WR8pMHObLVJEXRp7EOIxhJf1B5tYv9BwyzRswGL7/Dgd7vIm12YfpNVNJrVuf0Zx
        ovk0XTsYFdsNcoIkxOqJ4/WeZSaoM5bLpldDVfbSv+qZC9xVnio/ApJjSSbXbMRZ
        eoQzR+2xtoBM6zbYlGEW2nALqgIo9xjfXMRIlrdbujVdIyomIdqAQriMU3yD6v82
        L/1c7TbthHK8AEjGlXzJ7tGL0dcSIcrNhts2djucsO2vRekCAwEAAaNTMFEwHQYD
        VR0OBBYEFJemKcn2GrmrXf/c6QzHgfW6AnSiMB8GA1UdIwQYMBaAFJemKcn2Grmr
        Xf/c6QzHgfW6AnSiMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
        AIAWVhWxKp/vxBTJtmY/DJm+3bFH+zcYikOHEGn28hhbL7noINN1UGeA2nAA0m1C
        cT+tVCYxztwH8A46SxJ+SKY5fkfWiSGkRQt/nQUcVgga6k851yhCS7jQ8QM5qtvd
        12Rfohwpm2iLiDFLvmUK2C1T4faBMaaJRuuVKCPM7v5so6z3eTLh7bLnoxSbBtKV
        6oQliMX2J9pMT1g0ILhU/9NypvLpf6fsRyM128cB0+5AUIdtAALymwIrc6aKALum
        cY7v7e7TzkKfnW+KIkJkdjxevHxCHob0TpiMo95ok3QZbmG027YE2+VN46JheZAz
        uxkOVPWSzrSt0loNHu7Hkok=
        -----END CERTIFICATE-----
      tls.key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC5H36cLoyQvn0y
        vpxUtEbSrbhMhj8fm4HlyHJc8IIO3Ll4NhPpiEXTVGx9bNQasFVXgwDzyD3wj5j+
        0REKDCkyVBru5A2rlQOuZRgSkFkfKTBzmy1SRF0aexDiMYSX9QebWL/QcMs0bMBi
        +/w4He7yJtdmH6TVTSa1bn9GcaL5NF07GBXbDXKCJMTqieP1nmUmqDOWy6ZXQ1X2
        0r/qmQvcVZ4qPwKSY0km12zEWXqEM0ftsbaATOs22JRhFtpwC6oCKPcY31zESJa3
        W7o1XSMqJiHagEK4jFN8g+r/Ni/9XO027YRyvABIxpV8ye7Ri9HXEiHKzYbbNnY7
        nLDtr0XpAgMBAAECggEASJ4eIE3yPeU7X2h+EowVLBeRMBOJN3Dc57JVijeeDQ5w
        gsNT1EvseBWp6RmDqmR5VbbB7N8jzPXHYk3IjVRv5JoxZnx3EFOH+iUV6FJPY3XY
        18CLarX+f6C+4rvh82ne7gVGWRGl5I60eR+3tJupW7v4ysqm8jUtdgY+TvfMokxJ
        ZWncOo9SWnnoiOmt+DDNvNbdRw+W7OE7X5nS1wxqImSSB0BNtEHtYpNLFJkakDTy
        OT8rcUMx+MmsnLPjTCu6/kiZQe9FpBQbA1wUNbtYDg9ADo53k/72QnfjieIXf73P
        92fVYsKzcTwCP4jATuXU6DCiybp4wT54T24pzDbPcQKBgQDdSf7keb4YA1nsa+ta
        3rrxZ62zHKxr/MNxlZ0fkqGERvSwK43uJSgqYLsuWtgCocEthh9w9/C2KRCV72ba
        eDN+iDyfhaOXJzxREwl2BhRNEpMg5EFaKMJnsp2ob5RtioeJiqjUZCixDHYShgs9
        2GKrGcM7QHwOr6K3Eit3C0SsRwKBgQDWKTqiqHRO90gMIOmXDULo/rQjNhSSsjU+
        lz/g8T9qHqcHm846LooCzoxGTMj5mqxklvUgrwzzAzqyLpsCKIdb7oPydNYf/6eL
        ypGu4GHA2QFRNI7AEWBsboDoUvOZuNhW/oX25GR8Kqyl5qmpXm6exdtRgWIiYADz
        UqTL2EsETwKBgEoYVLi76uKvfJSlLhEnMwFR7d9jYnhmEiseJZZEysA34gZ7DvMG
        jgRij0peMKXw83YCytRQsNDNvzf1CUNtrBBaHbJsVPJvuMqMzUYvkuybo5gH1boS
        m8WNES0s704ebHOpcg5r2xQtT/uz1l/G7ILOBYj5dpCUTq9t7g/WPhBRAoGAV7bH
        Nzu7d2Q8dAs+4QkjcH5xlUJfJr4qpJoaJa1phbNMQgeEbbwF9qRWO6zTW7gIB6L0
        fxBzQ0z9S2FfR4EF/5cvH6zOzohNPSoYhQGNyAiZS4M1PGFhlsejsIPZFgrpQKg6
        giaFKX3o/IH+10nAEPOEoltVsDKV8RLWQE80Wm0CgYAiDl8uGRj6XCkuqg9Piahi
        x1qlxlK/KjSxIgjd1DKXVxqxL5mf4HDDOV7JKlhZRHTmVS9WtJUrU7bsddq1fYka
        udJMXTCyqbkr0jq3Uvc6TO8byGR8V34fy9zuWTWdQquIVI5KraCDqr9f5inM6U0l
        nuQxZcsXdixK4GkH72/D+w==
        -----END PRIVATE KEY-----
