apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-gemma-serving
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/02-apps/main/gemma-serving/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: private-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
        istio.io/use-waypoint: waypoint
