apiVersion: v1
kind: Service
metadata:
  name: qwen-inference
  namespace: private-assistant
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
    protocol: TCP
  selector:
    app: qwen-inference
