apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-main-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/yhjh5302/gitops.git'
      revision: HEAD
      directories:
      - path: gitops/01-system/main/*
      - path: gitops/02-apps/main/*
      - path: gitops/02-apps/main/gemma-serving
        exclude: true
  template:
    metadata:
      name: 'root-main-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/yhjh5302/gitops.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
