apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-istio-istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/shared-charts/istio/charts/istiod
    helm:
      releaseName: istiod
      values: |
        profile: ambient
        meshConfig:
          extensionProviders:
          - name: oauth2-proxy
            envoyExtAuthzHttp:
              service: oauth2-proxy.oauth2-proxy.svc.cluster.local
              port: 80
              pathPrefix: /oauth2/auth
              headersToDownstreamOnDeny:
              - content-type
              - set-cookie
              headersToUpstreamOnAllow:
              - authorization
              - cookie
              - x-auth-request-user
              - x-auth-request-email
              includeHeadersInCheck:
              - cookie
              - authorization
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks
