apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-istio-cni
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/shared-charts/istio/charts/cni
    helm:
      releaseName: istio-cni
      values: |
        profile: ambient
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
