# SPDX-License-Identifier: Apache-2.0
{{- if include "mysql.pdbEnabled" . }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  {{- if and (eq .Values.architecture "replication") .Values.replication.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.replication.pdb.maxUnavailable }}
  {{- else if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else if eq .Values.architecture "replication" }}
  minAvailable: {{ .Values.replication.pdb.minAvailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
{{- end }}
