# SPDX-License-Identifier: Apache-2.0
{{- include "mysql.validateExternalSecrets" . }}
{{- if not (or .Values.auth.existingSecret (include "mysql.authSecretManagedByExternalSecret" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.secretName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.existingSecretRootPasswordKey }}: {{ include "mysql.rootPassword" . | b64enc | quote }}
  {{ .Values.auth.existingSecretUserPasswordKey }}: {{ include "mysql.userPassword" . | b64enc | quote }}
  {{ .Values.auth.existingSecretReplicationPasswordKey }}: {{ include "mysql.replicationPassword" . | b64enc | quote }}
{{- end }}
{{- if and (include "mysql.backupEnabled" .) (not .Values.backup.s3.existingSecret) (not (include "mysql.backupSecretManagedByExternalSecret" .)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.backupSecretName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.backup.s3.existingSecretAccessKeyKey }}: {{ .Values.backup.s3.accessKey | quote }}
  {{ .Values.backup.s3.existingSecretSecretKeyKey }}: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
