# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.clientServiceName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
  selector:
    {{- include "mysql.componentLabels" (dict "root" . "role" (ternary "source" "standalone" (eq .Values.architecture "replication"))) | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.metricsServiceName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
    monitoring.helmforge.dev/enabled: "true"
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "mysql.componentLabels" (dict "root" . "role" (ternary "source" "standalone" (eq .Values.architecture "replication"))) | nindent 4 }}
{{- end }}
{{- if eq .Values.architecture "replication" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.sourceServiceName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- with .Values.service.sourceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
  selector:
    {{- include "mysql.componentLabels" (dict "root" . "role" "source") | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.sourceMetricsServiceName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
    monitoring.helmforge.dev/enabled: "true"
    app.kubernetes.io/role: source
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "mysql.componentLabels" (dict "root" . "role" "source") | nindent 4 }}
{{- end }}
{{- if gt (int .Values.replication.readReplicas.replicaCount) 0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.replicasServiceName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- with .Values.service.replicasAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
  selector:
    {{- include "mysql.componentLabels" (dict "root" . "role" "replica") | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.replicasMetricsServiceName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
    monitoring.helmforge.dev/enabled: "true"
    app.kubernetes.io/role: replica
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "mysql.componentLabels" (dict "root" . "role" "replica") | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
