apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-qwen-inference
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # GitOps repository URL
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/02-apps/main/qwen-inference/manifests
  destination:
    # Target workload cluster API server URL
    # e.g., 'https://<api-server-ip>:6443'
    server: 'https://kubernetes.default.svc'
    namespace: private-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
