# SPDX-License-Identifier: Apache-2.0
architecture: replication

auth:
  existingSecret: postgresql-auth

replication:
  primary:
    persistence:
      enabled: true
      size: 50Gi
  readReplicas:
    replicaCount: 2
    persistence:
      enabled: true
      size: 50Gi

pdb:
  enabled: true
  minAvailable: 1
