# SPDX-License-Identifier: Apache-2.0
architecture: replication

auth:
  existingSecret: postgresql-auth

tls:
  enabled: true
  existingSecret: postgresql-tls
  sslMode: require

networkPolicy:
  enabled: true

replication:
  primary:
    persistence:
      enabled: true
      size: 100Gi
    probes:
      requireWritable: true
  readReplicas:
    replicaCount: 2
    persistence:
      enabled: true
      size: 100Gi
    probes:
      requireRecoveryMode: true
  wal:
    keepSize: 2GB
    maxSenders: 16
    maxReplicationSlots: 16
  pdb:
    enabled: true
    minAvailable: 1

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
