apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: postgres
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: postgres
      property: postgres-password
  - secretKey: keycloak-database-password
    remoteRef:
      key: keycloak
      property: database-password
  - secretKey: mlflow-database-password
    remoteRef:
      key: mlflow
      property: database-password
  - secretKey: argo-database-password
    remoteRef:
      key: argo-workflows
      property: database-password
  - secretKey: private-assistant-database-password
    remoteRef:
      key: private-assistant
      property: database-password
