apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:18-alpine
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-password
        - name: KEYCLOAK_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: keycloak-database-password
        - name: MLFLOW_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: mlflow-database-password
        - name: ARGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: argo-database-password
        - name: PRIVATE_ASSISTANT_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: private-assistant-database-password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: pgdata
        - mountPath: /docker-entrypoint-initdb.d
          name: init-scripts
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-scripts
        configMap:
          name: postgres-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
