apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sub-cloudflared-tunnel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/02-apps/sub/cloudflared-tunnel/manifests
  destination:
    server: '{{server}}'
    namespace: private-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
