# SPDX-License-Identifier: Apache-2.0
mode: production

hostname:
  hostname: https://sso.example.com

postgresql:
  enabled: true
  auth:
    database: keycloak
    username: keycloak
    password: testpassword

deployment:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

serviceAccount:
  automountServiceAccountToken: false

truststore:
  kubernetes:
    enabled: false

capacity:
  profile: small
