apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-mlflow-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Run after Vault and ESO deployment
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # GitOps repository URL
    repoURL: 'https://github.com/yhjh5302/gitops.git'
    targetRevision: HEAD
    path: gitops/01-system/main/mlflow/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
